version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: todolist-postgres
    environment:
      POSTGRES_DB: todo_dev
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: todo123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./packages/shared/src/infrastructure/database/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U todo -d todo_dev"]
      interval: 5s
      timeout: 3s
      retries: 10

  localstack:
    image: localstack/localstack:3.4
    container_name: todolist-localstack
    environment:
      SERVICES: cognito-idp,apigateway,lambda,ssm
      DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      DEBUG: 0
    ports:
      - "4566:4566"
    volumes:
      - localstack_data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  postgres_data:
  localstack_data:
